export global NavigationAdapter {
    out property <int> current-page;

    public function next-page() {
        root.current-page += 1;
    }

    public function previous-page() {
        root.current-page = max(0, root.current-page - 1);
    }
}

export component CardView {
    Rectangle {
        background: red;
        height: 100%;
        x: -(NavigationAdapter.current-page * root.width);
        width: 2 * root.width;

        i-touch-area := TouchArea {
            clicked => {
                debug("Hi??");
                NavigationAdapter.next-page();
            }
        }

        if self.x > -root.width : Rectangle {
            background: blue;
            x: 0;
            width: root.width;
            height: root.height;

            Text {
                text: "A";
            }
        }

        if self.x < 0 : Rectangle {
            background: orange;
            x: root.width;
            width: root.width;
            height: root.height;

            Text {
                text: "B";
            }
        }

        animate x {
            duration: 0.1s;
            easing: cubic-bezier(0.3, 0.0, 0.8, 0.15);
        }
    }
}
