[package]
name = "hcui"
version = "0.1.0"
edition = "2024"

[dependencies]
gilrs = "0.11.0"
rquickjs = { version = "0.9.0", features = ["bindgen"] }
slint = "1.11.0"

[build-dependencies]
slint-build = "1.11.0"
