import { StatusBar } from "./components/status-bar/status-bar.slint";
import { CardView } from "./components/card-view.slint";

export component MainWindow inherits Window {
    // callback clicked <=> i-touch-area.clicked;
    callback button(newText: string);

    in property <int> screen-width;
    in property <int> screen-height;

    width: screen-width * 1px;
    height: screen-height * 1px;
    title: "Hello World!";

    //property <string> text: "Hello, World!";

    // i-touch-area := TouchArea {
    //     clicked => {
    //         debug("ROOTCLICK?")
    //     }
    // }

    // button(newText) => {
    //     t.text = newText;
    // }

    VerticalLayout {
        spacing: 0px;
        alignment: LayoutAlignment.stretch;

        StatusBar {

        }
        // Rectangle {
        //     background: black;
        //     vertical-stretch: 1;

            // t := Text {
            //     text: "Hello, World!";
            //     font-size: 28pt;
            //     color: white;
            // }
        CardView {

        }
        // }
        Rectangle {
            height: 48px;
            background: purple;
        }
    }
}
